/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_remember;

import java.util.Scanner;

import java_remember.Abstracts.Worker;
import java_remember.Interfaces.IAgent;
import java_remember.Interfaces.IBuilding;
import java_remember.Model.Lab;
import java_remember.Model.WorkerBuilder;

public class App {
    public static void main(String[] args) {
        
        
    }

    
}
